name: ts-pkg # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The Tomorrow's Study Package Manager # 79 char long summary
description: |
  This Package Manager allows the ability to get/update the Tomorrow's 
  Study Content directly to your system.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  ts-pkg:
    plugin: rust
    source: .

apps: 
  ts-pkg: 
    command: 
